"""Additional release-group inputs used only for cases 1,501 onward."""

from __future__ import annotations


def spec(
    category: str,
    album: str,
    artist: str,
    cohort: str,
    language: str,
    era: str,
) -> dict[str, str]:
    return {
        "category": category,
        "album": album,
        "artist": artist,
        "cohort": cohort,
        "language": language,
        "era": era,
        "dataset_generation": "representative_3000",
    }


REPRESENTATIVE_SPECS_3000: list[dict[str, str]] = [
    # Rock, punk, post-punk and experimental guitar music.
    spec("default", "Marquee Moon", "Television", "rock_alternative", "en", "1970s"),
    spec("default", "Horses", "Patti Smith", "rock_alternative", "en", "1970s"),
    spec("default", "London Calling", "The Clash", "rock_alternative", "en", "1970s"),
    spec("default", "Unknown Pleasures", "Joy Division", "rock_alternative", "en", "1970s"),
    spec("default", "Entertainment!", "Gang of Four", "rock_alternative", "en", "1970s"),
    spec("default", "The Stone Roses", "The Stone Roses", "rock_alternative", "en", "1980s"),
    spec("default", "Surfer Rosa", "Pixies", "rock_alternative", "en", "1980s"),
    spec("default", "Daydream Nation", "Sonic Youth", "rock_alternative", "en", "1980s"),
    spec("default", "The Bends", "Radiohead", "rock_alternative", "en", "1990s"),
    spec("default", "In the Aeroplane Over the Sea", "Neutral Milk Hotel", "rock_alternative", "en", "1990s"),
    spec("default", "Turn On the Bright Lights", "Interpol", "rock_alternative", "en", "2000s"),
    spec("default", "American Idiot", "Green Day", "rock_alternative", "en", "2000s"),
    spec("default", "Sound of Silver", "LCD Soundsystem", "rock_alternative", "en", "2000s"),
    spec("default", "Fetch the Bolt Cutters", "Fiona Apple", "rock_alternative", "en", "2020s"),
    spec("default", "Dragon New Warm Mountain I Believe in You", "Big Thief", "rock_alternative", "en", "2020s"),

    # Pop, R&B and contemporary vocal music.
    spec("default", "Off the Wall", "Michael Jackson", "pop_rnb", "en", "1970s"),
    spec("default", "Control", "Janet Jackson", "pop_rnb", "en", "1980s"),
    spec("default", "Butterfly", "Mariah Carey", "pop_rnb", "en", "1990s"),
    spec("default", "Mama’s Gun", "Erykah Badu", "pop_rnb", "en", "2000s"),
    spec("default", "A Seat at the Table", "Solange", "pop_rnb", "en", "2010s"),
    spec("default", "Metamodern Sounds in Country Music", "Sturgill Simpson", "country_folk", "en", "2010s"),
    spec("default", "After Hours", "The Weeknd", "pop_rnb", "en", "2020s"),
    spec("default", "folklore", "Taylor Swift", "pop_rnb", "en", "2020s"),
    spec("default", "SOUR", "Olivia Rodrigo", "pop_rnb", "en", "2020s"),
    spec("default", "BRAT", "Charli xcx", "pop_rnb", "en", "2020s"),

    # Hip-hop from different regions and generations.
    spec("default", "It Takes a Nation of Millions to Hold Us Back", "Public Enemy", "hiphop", "en", "1980s"),
    spec("default", "3 Feet High and Rising", "De La Soul", "hiphop", "en", "1980s"),
    spec("default", "The Score", "Fugees", "hiphop", "en", "1990s"),
    spec("default", "Black on Both Sides", "Mos Def", "hiphop", "en", "1990s"),
    spec("default", "Donuts", "J Dilla", "hiphop", "instrumental", "2000s"),
    spec("default", "Run the Jewels 2", "Run the Jewels", "hiphop", "en", "2010s"),
    spec("default", "DAMN.", "Kendrick Lamar", "hiphop", "en", "2010s"),
    spec("default", "Daytona", "Pusha T", "hiphop", "en", "2010s"),
    spec("default", "IGOR", "Tyler, the Creator", "hiphop", "en", "2010s"),

    # Electronic, ambient and experimental music.
    spec("default", "Moon Safari", "Air", "electronic", "en", "1990s"),
    spec("default", "Endtroducing.....", "DJ Shadow", "electronic", "instrumental", "1990s"),
    spec("default", "Richard D. James Album", "Aphex Twin", "electronic", "instrumental", "1990s"),
    spec("default", "Geogaddi", "Boards of Canada", "electronic", "instrumental", "2000s"),
    spec("default", "Rounds", "Four Tet", "electronic", "instrumental", "2000s"),
    spec("default", "Cosmogramma", "Flying Lotus", "electronic", "instrumental", "2010s"),
    spec("default", "Syro", "Aphex Twin", "electronic", "instrumental", "2010s"),
    spec("default", "Oil of Every Pearl’s Un-Insides", "SOPHIE", "electronic", "en", "2010s"),
    spec("default", "KiCk i", "Arca", "electronic", "multi", "2020s"),
    spec("default", "Promises", "Floating Points, Pharoah Sanders & The London Symphony Orchestra", "experimental", "instrumental", "2020s"),

    # Jazz and vocal standards, including long-form recordings.
    spec("default", "Moanin’", "Art Blakey & The Jazz Messengers", "jazz_blues", "instrumental", "1950s"),
    spec("default", "Somethin’ Else", "Cannonball Adderley", "jazz_blues", "instrumental", "1950s"),
    spec("default", "The Shape of Jazz to Come", "Ornette Coleman", "jazz_blues", "instrumental", "1950s"),
    spec("default", "Blue Train", "John Coltrane", "jazz_blues", "instrumental", "1950s"),
    spec("default", "Sarah Vaughan", "Sarah Vaughan", "jazz_blues", "en", "1950s"),
    spec("default", "Karma", "Pharoah Sanders", "jazz_blues", "instrumental", "1960s"),
    spec("default", "Bitches Brew", "Miles Davis", "jazz_blues", "instrumental", "1970s"),
    spec("default", "Ptah, the El Daoud", "Alice Coltrane", "jazz_blues", "instrumental", "1970s"),
    spec("default", "Heavy Weather", "Weather Report", "jazz_blues", "instrumental", "1970s"),

    # Spanish, Portuguese and Latin American catalog.
    spec("default", "La grasa de las capitales", "Serú Girán", "latin", "es", "1970s"),
    spec("default", "Transa", "Caetano Veloso", "latin", "pt", "1970s"),
    spec("default", "Alucinação", "Belchior", "latin", "pt", "1970s"),
    spec("default", "Elis & Tom", "Elis Regina & Antonio Carlos Jobim", "latin", "pt", "1970s"),
    spec("default", "A tábua de esmeralda", "Jorge Ben", "latin", "pt", "1970s"),
    spec("default", "Cosa nuestra", "Willie Colón", "latin", "es", "1970s"),
    spec("default", "Piano bar", "Charly García", "latin", "es", "1980s"),
    spec("default", "Dynamo", "Soda Stereo", "latin", "es", "1990s"),
    spec("default", "Giros", "Fito Páez", "latin", "es", "1980s"),
    spec("default", "Lágrimas negras", "Bebo Valdés & Diego el Cigala", "latin", "es", "2000s"),
    spec("default", "Musas", "Natalia Lafourcade", "latin", "es", "2010s"),
    spec("default", "De todas las flores", "Natalia Lafourcade", "latin", "es", "2020s"),

    # African, Middle Eastern, Asian and non-English catalog.
    spec("default", "Zombie", "Fela Kuti", "africa_middle_east", "yo", "1970s"),
    spec("default", "Moffou", "Salif Keita", "africa_middle_east", "bm", "2000s"),
    spec("default", "Dimanche à Bamako", "Amadou & Mariam", "africa_middle_east", "fr", "2000s"),
    spec("default", "Aman Iman", "Tinariwen", "africa_middle_east", "tmh", "2000s"),
    spec("default", "African Giant", "Burna Boy", "africa_middle_east", "en", "2010s"),
    spec("default", "Multitude", "Stromae", "world_nonenglish", "fr", "2020s"),
    spec("default", "L’Imprudence", "Alain Bashung", "world_nonenglish", "fr", "2000s"),
    spec("default", "Die Mensch‐Maschine", "Kraftwerk", "world_nonenglish", "de", "1970s"),
    spec("default", "NEU!", "NEU!", "world_nonenglish", "de", "1970s"),
    spec("default", "Solid State Survivor", "Yellow Magic Orchestra", "east_asia", "ja", "1970s"),
    spec("default", "Scenery", "Ryo Fukui", "east_asia", "instrumental", "1970s"),
    spec("default", "A LONG VACATION", "Eiichi Ohtaki", "east_asia", "ja", "1980s"),
    spec("default", "FOR YOU", "Tatsuro Yamashita", "east_asia", "ja", "1980s"),
    spec("default", "Fantasma", "Cornelius", "east_asia", "ja", "1990s"),
    spec("default", "Modern Times", "IU", "east_asia", "ko", "2010s"),
    spec("default", "LILAC", "IU", "east_asia", "ko", "2020s"),
    spec("default", "4 Walls", "f(x)", "east_asia", "ko", "2010s"),
    spec("default", "Love Yourself 轉 ‘Tear’", "BTS", "east_asia", "ko", "2010s"),
    spec("default", "0", "Ichiko Aoba", "east_asia", "ja", "2020s"),

    # Film, television and game scores.
    spec("default", "The Lord of the Rings: The Fellowship of the Ring", "Howard Shore", "classical_soundtrack", "instrumental", "2000s"),
    spec("default", "Princess Mononoke", "Joe Hisaishi", "classical_soundtrack", "instrumental", "1990s"),
    spec("default", "Cowboy Bebop", "The Seatbelts", "classical_soundtrack", "instrumental", "1990s"),
    spec("default", "Minecraft: Volume Alpha", "C418", "classical_soundtrack", "instrumental", "2010s"),
    spec("default", "The Last of Us", "Gustavo Santaolalla", "classical_soundtrack", "instrumental", "2010s"),
    spec("default", "Hollow Knight", "Christopher Larkin", "classical_soundtrack", "instrumental", "2010s"),

    # Live releases across jazz, soul, rock, metal and regional catalogs.
    spec("live", "Kick Out the Jams", "MC5", "live", "en", "1960s"),
    spec("live", "Ella in Berlin", "Ella Fitzgerald", "live", "en", "1960s"),
    spec("live", "Nina Simone at Town Hall", "Nina Simone", "live", "en", "1960s"),
    spec("live", "Live at the Village Vanguard", "John Coltrane", "live", "instrumental", "1960s"),
    spec("live", "Donny Hathaway Live", "Donny Hathaway", "live", "en", "1970s"),
    spec("live", "Live at Carnegie Hall", "Bill Withers", "live", "en", "1970s"),
    spec("live", "Aretha Live at Fillmore West", "Aretha Franklin", "live", "en", "1970s"),
    spec("live", "Curtis/Live!", "Curtis Mayfield", "live", "en", "1970s"),
    spec("live", "Live and Dangerous", "Thin Lizzy", "live", "en", "1970s"),
    spec("live", "Agharta", "Miles Davis", "live", "instrumental", "1970s"),
    spec("live", "Caetano e Chico juntos e ao vivo", "Caetano Veloso & Chico Buarque", "live", "pt", "1970s"),
    spec("live", "101", "Depeche Mode", "live", "en", "1980s"),
    spec("live", "Mercedes Sosa en Argentina", "Mercedes Sosa", "live", "es", "1980s"),
    spec("live", "S&M", "Metallica", "live", "en", "1990s"),
    spec("live", "From the Muddy Banks of the Wishkah", "Nirvana", "live", "en", "1990s"),
    spec("live", "Live on Two Legs", "Pearl Jam", "live", "en", "1990s"),
    spec("live", "98.12.28 男達の別れ", "Fishmans", "live", "ja", "1990s"),
    spec("live", "I Might Be Wrong: Live Recordings", "Radiohead", "live", "en", "2000s"),
    spec("live", "Score", "Dream Theater", "live", "en", "2000s"),
    spec("live", "Live in Buenos Aires", "Coldplay", "live", "en", "2010s"),
    spec("live", "Live at the Apollo", "Arctic Monkeys", "live", "en", "2000s"),
    spec("live", "Live at the Royal Albert Hall", "Snarky Puppy", "live", "instrumental", "2020s"),

    # Remix, dub and edit collections. Exact named versions remain distinct.
    spec("remix", "Love and Dancing", "The League Unlimited Orchestra", "remix", "en", "1980s"),
    spec("remix", "Disco", "Pet Shop Boys", "remix", "en", "1980s"),
    spec("remix", "janet. Remixed", "Janet Jackson", "remix", "en", "1990s"),
    spec("remix", "Fixed", "Nine Inch Nails", "remix", "en", "1990s"),
    spec("remix", "Things Falling Apart", "Nine Inch Nails", "remix", "en", "2000s"),
    spec("remix", "Silent Alarm Remixed", "Bloc Party", "remix", "en", "2000s"),
    spec("remix", "We Are Glitter", "Goldfrapp", "remix", "en", "2000s"),
    spec("remix", "All Back to the Mine", "Moloko", "remix", "en", "2000s"),
    spec("remix", "Boombox", "Kylie Minogue", "remix", "en", "2000s"),
    spec("remix", "This Is the Remix", "Destiny’s Child", "remix", "en", "2000s"),
    spec("remix", "Good Girl Gone Bad: The Remixes", "Rihanna", "remix", "en", "2000s"),
    spec("remix", "Recharged", "Linkin Park", "remix", "en", "2010s"),
    spec("remix", "Dross Glop", "Battles", "remix", "instrumental", "2010s"),
    spec("remix", "Crooked Machine", "Róisín Murphy", "remix", "en", "2020s"),
    spec("remix", "Finally Enough Love: 50 Number Ones", "Madonna", "remix", "en", "2020s"),
    spec("remix", "Star Rise", "Nusrat Fateh Ali Khan", "remix", "pa", "1990s"),
    spec("remix", "Bebel Gilberto Remixed", "Bebel Gilberto", "remix", "pt", "2000s"),
    spec("remix", "Babylon Rewound", "Thievery Corporation", "remix", "multi", "2000s"),
    spec("remix", "Inspiración Espiración", "Gotan Project", "remix", "es", "2000s"),
    spec("remix", "Viva Elvis", "Elvis Presley", "remix", "en", "2010s"),
    spec("remix", "Bob Marley & The Wailers Remixed", "Bob Marley & The Wailers", "remix", "en", "2000s"),
    spec("remix", "Self Defence", "UNKLE", "remix", "en", "2000s"),

    # Albums or projects whose requested identity is a cover performance.
    spec("cover", "These Foolish Things", "Bryan Ferry", "cover", "en", "1970s"),
    spec("cover", "Through the Looking Glass", "Siouxsie and the Banshees", "cover", "en", "1980s"),
    spec("cover", "McLemore Avenue", "Booker T. & the M.G.’s", "cover", "instrumental", "1970s"),
    spec("cover", "Stardust", "Willie Nelson", "cover", "en", "1970s"),
    spec("cover", "Jukebox", "Cat Power", "cover", "en", "2000s"),
    spec("cover", "Nouvelle Vague", "Nouvelle Vague", "cover", "multi", "2000s"),
    spec("cover", "Dub Side of the Moon", "Easy Star All‐Stars", "cover", "en", "2000s"),
    spec("cover", "Radiodread", "Easy Star All‐Stars", "cover", "en", "2000s"),
    spec("cover", "The Life Aquatic Studio Sessions", "Seu Jorge", "cover", "pt", "2000s"),
    spec("cover", "A Foreign Sound", "Caetano Veloso", "cover", "en", "2000s"),
    spec("cover", "1989", "Ryan Adams", "cover", "en", "2010s"),
    spec("cover", "Rebuild the Wall", "Luther Wright & The Wrongs", "cover", "en", "2000s"),
    spec("cover", "Petra Haden Sings: The Who Sell Out", "Petra Haden", "cover", "en", "2000s"),
    spec("cover", "Tusk", "Camper Van Beethoven", "cover", "en", "2000s"),
    spec("cover", "American IV: The Man Comes Around", "Johnny Cash", "cover", "en", "2000s"),

    # Acoustic and unplugged releases in English, Spanish and Portuguese.
    spec("acoustic", "MTV Unplugged", "10,000 Maniacs", "acoustic", "en", "1990s"),
    spec("acoustic", "MTV Unplugged", "Tony Bennett", "acoustic", "en", "1990s"),
    spec("acoustic", "Unplugged", "The Corrs", "acoustic", "en", "1990s"),
    spec("acoustic", "Unplugged", "Alicia Keys", "acoustic", "en", "2000s"),
    spec("acoustic", "Unplugged", "JAY‐Z", "acoustic", "en", "2000s"),
    spec("acoustic", "MTV Unplugged", "Florence + the Machine", "acoustic", "en", "2010s"),
    spec("acoustic", "MTV Unplugged", "Biffy Clyro", "acoustic", "en", "2010s"),
    spec("acoustic", "MTV Unplugged", "Ricky Martin", "acoustic", "es", "2000s"),
    spec("acoustic", "MTV Unplugged", "Juanes", "acoustic", "es", "2010s"),
    spec("acoustic", "Maná MTV Unplugged", "Maná", "acoustic", "es", "1990s"),
    spec("acoustic", "Los Tres MTV Unplugged", "Los Tres", "acoustic", "es", "1990s"),
    spec("acoustic", "Hello! MTV Unplugged", "Charly García", "acoustic", "es", "1990s"),
    spec("acoustic", "MTV Unplugged", "Café Tacvba", "acoustic", "es", "1990s"),
    spec("acoustic", "Acústico MTV", "Gilberto Gil", "acoustic", "pt", "1990s"),
    spec("acoustic", "Acústico MTV", "Lenine", "acoustic", "pt", "2000s"),
    spec("acoustic", "Acústico MTV", "Engenheiros do Hawaii", "acoustic", "pt", "2000s"),
    spec("acoustic", "Acústico MTV", "Ira!", "acoustic", "pt", "2000s"),
    spec("acoustic", "Acústico MTV", "Marcelo D2", "acoustic", "pt", "2000s"),
    spec("acoustic", "Acústico MTV", "Skank", "acoustic", "pt", "2000s"),
    spec("acoustic", "Cuttin’ Grass, Vol. 1", "Sturgill Simpson", "acoustic", "en", "2020s"),

    # Demos, outtakes, sessions and deliberately alternate versions.
    spec("alternate", "With the Lights Out", "Nirvana", "alternate", "en", "2000s"),
    spec("alternate", "The Complete In a Silent Way Sessions", "Miles Davis", "alternate", "instrumental", "2000s"),
    spec("alternate", "Both Directions at Once: The Lost Album", "John Coltrane", "alternate", "instrumental", "2010s"),
    spec("alternate", "The Lost Tapes", "Nas", "alternate", "en", "2000s"),
    spec("alternate", "New Moon", "Elliott Smith", "alternate", "en", "2000s"),
    spec("alternate", "Family Tree", "Nick Drake", "alternate", "en", "2000s"),
    spec("alternate", "4‐Track Demos", "PJ Harvey", "alternate", "en", "1990s"),
    spec("alternate", "The Promise", "Bruce Springsteen", "alternate", "en", "2010s"),
    spec("alternate", "Tracks", "Bruce Springsteen", "alternate", "en", "1990s"),
    spec("alternate", "South Saturn Delta", "Jimi Hendrix", "alternate", "en", "1990s"),
    spec("alternate", "Valleys of Neptune", "Jimi Hendrix", "alternate", "en", "2010s"),
    spec("alternate", "Hawthorne, CA", "The Beach Boys", "alternate", "en", "2000s"),
    spec("alternate", "The Stooges: The Complete Fun House Sessions", "The Stooges", "alternate", "en", "1990s"),
    spec("alternate", "The Lost Tapes", "Can", "alternate", "en", "2010s"),
    spec("alternate", "Hitchhiker", "Neil Young", "alternate", "en", "2010s"),
    spec("alternate", "The Greatest Gift", "Sufjan Stevens", "alternate", "en", "2010s"),
    spec("alternate", "Originals", "Prince", "alternate", "en", "2010s"),
    spec("alternate", "Toy", "David Bowie", "alternate", "en", "2020s"),
    spec("alternate", "Tell Tale Signs", "Bob Dylan", "alternate", "en", "2000s"),
    spec("alternate", "The Nashville Sessions", "Townes Van Zandt", "alternate", "en", "1990s"),
]
